from enum import StrEnum


class MessageCode(StrEnum):
    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    ADMIN_CREATED = "ADMIN_CREATED"
    DELIVERY_PARTNER_CREATED = "DELIVERY_PARTNER_CREATED"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"

    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    USERNAME_EXISTS = "USERNAME_EXISTS"
    PROFILE_FETCHED = "PROFILE_FETCHED"

    USERS_FETCHED = "USERS_FETCHED"
    USER_FETCHED = "USER_FETCHED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
    USER_NOT_FOUND = "USER_NOT_FOUND"

    ORDER_CREATED = "ORDER_CREATED"
    ORDERS_FETCHED = "ORDERS_FETCHED"
    ORDER_FETCHED = "ORDER_FETCHED"
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    ORDER_STATUS_UPDATED = "ORDER_STATUS_UPDATED"
